import fs from 'fs';
import readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('=== WooCommerce Integration Configurator ===');

rl.question('1. Enter your WordPress store URL (e.g., https://yourdomain.com): ', (siteUrl) => {
  // Clean URL and append the WooCommerce REST API endpoint
  let cleanUrl = siteUrl.trim().replace(/\/$/, '');
  if (!cleanUrl.startsWith('http://') && !cleanUrl.startsWith('https://')) {
    cleanUrl = 'https://' + cleanUrl;
  }
  const apiUrl = `${cleanUrl}/wp-json/wc/v3`;

  rl.question('2. Enter your WooCommerce Consumer Key (starts with ck_): ', (ck) => {
    rl.question('3. Enter your WooCommerce Consumer Secret (starts with cs_): ', (cs) => {
      rl.question('4. Enter your Flutterwave Public Key (starts with FLWPUBK_): ', (flwKey) => {
        const key = ck.trim();
        const secret = cs.trim();
        const flw = flwKey.trim();
        
        if (!key.startsWith('ck_') || !secret.startsWith('cs_')) {
          console.error('\nError: Invalid Consumer Key or Secret format. Please generate them in WooCommerce > Settings > Advanced > REST API.');
          rl.close();
          return;
        }

        // Generate the base64 auth token
        const rawToken = `${key}:${secret}`;
        const base64Token = Buffer.from(rawToken).toString('base64');

        const envContent = `# Generated by configure-wc script on ${new Date().toISOString()}
VITE_WC_URL=${apiUrl}
VITE_WC_AUTH=${base64Token}
VITE_FLUTTERWAVE_PUBLIC_KEY=${flw}
`;

        try {
          fs.writeFileSync('.env', envContent);
          console.log('\nSuccess! Created your `.env` file with base64 WooCommerce authorization credentials and Flutterwave key.');
          console.log(`URL: ${apiUrl}`);
          console.log('VITE_WC_AUTH generated successfully.');
          console.log(`Flutterwave Public Key: ${flw}\n`);
          console.log('To deploy these variables live, also add them as repository secrets in GitHub:');
          console.log('- Name: VITE_WC_URL  -> Value: ' + apiUrl);
          console.log('- Name: VITE_WC_AUTH -> Value: ' + base64Token);
          console.log('- Name: VITE_FLUTTERWAVE_PUBLIC_KEY -> Value: ' + flw);
        } catch (err) {
          console.error('Error writing .env file:', err);
        }

        rl.close();
      });
    });
  });
});
